name: Build Windows EXE

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile --name "ShadowAI" --icon=assets/icon.ico --noconsole run_shadow_gui.py
    - uses: actions/upload-artifact@v4
      with:
        name: ShadowAI
        path: dist/ShadowAI.exe